site_name: Ivy Docs
pages:
- Home: 'index.md'
- Staff Console: 'Staff-Console.md'
- Viewing Reports: 'Viewing-Reports.md'
- Searching For Guests: 'Searching-For-Guests.md'
- User Accounts: 'User-Accounts.md'
- Guest Profiles: 'Guest-Profiles.md'
- Messages: 'Messages.md'
- Self Check In: 'Self-Check-In.md'
- Hotel Setup Process: 'Hotel-Setup-Process.md'
- Ivy For Choice: 'Ivy-For-Choice.md'
- Managers: 'Managers.md'
- Agents: 'Agents.md'
- Best Practices: 'Best-Practices.md'
- Choice Advantage Guest Report: 'Choice-Advantage-Guest-Report.md'
theme: readthedocs