site_name: Ivy Docs
pages:
- getridofthis: 'notneeded.md'
- Home: 'index.md'
- Staff Console: 
  - 'What is the Staff Console?': 'staff-console/Staff-Console.md'
  - 'Getting To The Console': 'staff-console/Getting-To-The-Console.md' 
- User Accounts:
  - 'Signing Up': 'user-accounts/Signing-Up.md' 
  - 'Settings': 'user-accounts/Settings.md'
  - 'Forgot Password': 'user-accounts/Forgot-Password.md'
theme: readthedocs